# Generated by Django 4.1.3 on 2023-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_course_number_course_course_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuallyAddedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_population', models.IntegerField(default=0)),
            ],
        ),
    ]
